### ISSUE TITLE
Separate crate for handling common code

### ISSUE THREAD

**Issue by ogenev** [carver/trin#58]
Because I’m starting to work on implementing CLI parsing support for both networks, I’m thinking of what is the best way to structure the common code.

As we are moving forward to workspace architecture and because circular dependencies in packages are not possible (we can’t import root module in the current network packages, because the root depends on them), If we want more than one package to use the same module, it seems natural to just have a third common package, and both state and history to depend on it.

Let me know if this makes sense and we can add the third package to https://github.com/carver/trin/pull/57

**Comment by SamWilsn** [comment]
I renamed the issue to crate, because I _think_ that's what you mean?

So we'd have the crates `trin-state`, `trin-history`, and then create a `trin-core`?

**Comment by ogenev** [comment]
> I renamed the issue to crate, because I _think_ that's what you mean?
> 
> So we'd have the crates `trin-state`, `trin-history`, and then create a `trin-core`?

Yeah, and `trim-state` and `trin-history` will depend on `trin-core`.

**Comment by ogenev** [comment]
In chain history network implementation, we are planning to reuse probably more than 90% of the current state network code.

We have three options: available

**1) Copy and paste files from state to history package.**
- pros: 
   - Easy to implement, just copy/paste.
- cons: 
   - It will be harder to extract the common parts later and we will loose track which modification is implemented especially for trin-history.
   - Any change in core `trin state` code will not automatically downstream to `trin-history`.

**2) Import modules directly from state package.**
- pros:
   - easy to implement
- cons:
   - We will made `trin-history` dependent on `trin-state`, which is not what we want.

**3) Implement a core package which will handle the common modules and every network implementation will import from this package.**
- pros:
   - clear separation between core, state and history packages
   - Network specific modifications are easy to track
   - Merge conflicts friendly
- cons:
   - some overhead to make sure any change in core doesn't break `trin-state` implementation.

I'm probably missing some of the cons and pros, please feel free to add them.

This is [experimental PR](https://github.com/carver/trin/pull/60) which implements 3). I think now is the perfect timing to extract a separate core package, because it is likely that most of the portal networks will use the first 6 RPC messages - `PING/PONG`, `FINDNODES/NODES`, `FINDCONTENT/CONTENT` and any network specific messages from now on can just go into the network specific package.

We can have also some kind of merging/PR review policies, for example: _"Chain history team will not touch the core package, if we want to make any modification, we will import from core and modify the code in trin-history package"_ or "_Any modifications in core should be approved from trin core team before merging"._

I'm just trying to brainstorm here, please let me know how this sounds to you, am I missing something? Do we have to do this?

**Comment by mrferris** [comment]
This refactor is definitely what I think the repo should look like ultimately. But I also think that a lot of our immediate work for implementing a chain history POC involves changes to the files that are in `core/`, which sounds like a lot of gridlock up-front due to the review process going outside our sub-team.

I think that we should go with option 1 for right now because it aligns with the fact that we're making a chain history prototype, and not yet thinking too hard about what the full-fledged trin client that interacts with all of these networks is going to look like.

On the one hand it doesn't seem great to throw away git's usual merging abilities by using directories instead of branches (option 1), but on the other hand it seems like there are options for easily seeing diffs while merging two directories: [Stack Overflow question](https://stackoverflow.com/questions/10091858/git-merge-between-two-folders-not-branches)....so I don't think manually merging would be horrible, especially if we keep our changes to anything in `core/` succinct and organized well. 

Once we start thinking about the design of the full trin client (and not just prototyping the networks), I think we should do this refactor, and then we can work on a separate branch and do weekly/bi-weekly reviews of anything we need merged into `core/`.

**Comment by ogenev** [comment]
> But I also think that a lot of our immediate work for implementing a chain history POC involves changes to the files that are in `core/`, which sounds like a lot of gridlock up-front due to the review process going outside our sub-team.

The general idea is to use `trin-core` as a library in `trin-history`. 

If we want to reuse some module, struct or function without modifying it, we can just do: `use trin_core::bar::foo `in `trin-history` without copying any code. If we need to do some modifications which do not benefit `trin-state`, we can always copy code and create `trin-history` specific modules.

By implementing 3), I think we get best of both worlds - we can reuse what is already there and we can create what we need.
